version: '3'
services:
  db:
    image: mysql:latest
    volumes:
      - shinopai-sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/pai-chat
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  shinopai-sql:
